/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.TonKhoBUS;
import DAO.ChiTietCungCapDAO;
import DAO.NhaCungCapDAO;
import DAO.SanPhamDAO;
import DAO.khoDAO;
import DAO.tonKhoDAO;
import DTO.ChiTietCungCapDTO;
import DTO.ChiTietQuyenDTO;
import DTO.ChiTietTonKhoDTO;
import DTO.NhaCungCapDTO;
import DTO.SanPhamDTO;
import DTO.khoDTO;
import helper.DateHelper;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class PhanPhoiProduct extends javax.swing.JFrame {

    /**
     * Creates new form PhanPhoiProduct
     */
    private TonKhoBUS tkBUS = new TonKhoBUS();
    private List<ChiTietQuyenDTO> allowedActions;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public PhanPhoiProduct(List<ChiTietQuyenDTO> allowedActions) {
        initComponents();
        modelTable = (DefaultTableModel) tbSanPham.getModel();
        modelCbbNcc = (DefaultComboBoxModel) cbbNhaCungCap.getModel();
        modelCbbKho = (DefaultComboBoxModel) cbbKho.getModel();
        loadTable();
        this.allowedActions = allowedActions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        labelNCC = new javax.swing.JLabel();
        cbbNhaCungCap = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        labelKho = new javax.swing.JLabel();
        cbbKho = new javax.swing.JComboBox<>();
        txtDiaDiemKho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoLuongPhanPhoi = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTonKho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHÂN PHỐI SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);
        if (tbSanPham.getColumnModel().getColumnCount() > 0) {
            tbSanPham.getColumnModel().getColumn(0).setResizable(false);
            tbSanPham.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbSanPham.getColumnModel().getColumn(1).setResizable(false);
            tbSanPham.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNCC.setText("Nhà cung cấp");

        cbbNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhaCungCapActionPerformed(evt);
            }
        });

        labelKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKho.setText("Kho hàng hóa");

        cbbKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKhoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Số lượng phân phối");

        txtSoLuongPhanPhoi.setText(" ");
        txtSoLuongPhanPhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongPhanPhoiActionPerformed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnXacNhan.setText("XÁC NHẬN PHÂN PHỐI");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng tồn kho ");

        txtTonKho.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelNCC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelKho)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbKho, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(txtDiaDiemKho)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(txtSoLuongPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKho)
                    .addComponent(cbbKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaDiemKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuongPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKhoActionPerformed
        // TODO add your handling code here:
        if(cbbKho.getSelectedItem() != null ){
            String tenkho = cbbKho.getSelectedItem().toString();
            khoDTO kho = khoDAO.getInstance().getWareHouseByName(tenkho);
            txtDiaDiemKho.setText(kho.getDiaChi());
            String tenSP = tbSanPham.getValueAt( tbSanPham.getSelectedRow(), 1).toString();
            SanPhamDTO sp = SanPhamDAO.getInstance().selectProductByName(tenSP);
            String nameNCC = cbbNhaCungCap.getSelectedItem().toString();
            NhaCungCapDTO ncc = NhaCungCapDAO.getInstance().getNCCByName(nameNCC);
            int maNCC = ncc.getMaNhaCungCap();
            int soLuongTon = tonKhoDAO.getInstance().getTonKhoBySPvaNCC(sp.getMaSanPham(), maNCC, kho.getMaKho());
            txtTonKho.setText(String.valueOf(soLuongTon));
        }
        
        
        //ArrayList<ChiTietTonKhoDTO> inventories =  tonKhoDAO.getInstance().getDetailTonKho(idProduct, WIDTH, allowedActions);
        
        
    }//GEN-LAST:event_cbbKhoActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tbSanPham.getSelectedRow();
        if(row != -1){
            String tenSP = tbSanPham.getValueAt(row, 1).toString();
            SanPhamDTO sp = SanPhamDAO.getInstance().selectProductByName(tenSP);
            loadCbbNhaCungCap(sp.getMaSanPham());
        }
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void cbbNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhaCungCapActionPerformed
        // TODO add your handling code here:
        if(cbbNhaCungCap.getSelectedItem() != null){
            String tenSP = tbSanPham.getValueAt( tbSanPham.getSelectedRow(), 1).toString();
            SanPhamDTO sp = SanPhamDAO.getInstance().selectProductByName(tenSP);
            String nameNCC = cbbNhaCungCap.getSelectedItem().toString();
            NhaCungCapDTO ncc = NhaCungCapDAO.getInstance().getNCCByName(nameNCC);
            int maNCC = ncc.getMaNhaCungCap();
            int donGia = ChiTietCungCapDAO.getInstance().findDonGia(maNCC, sp.getMaSanPham());
            txtDonGia.setText(String.valueOf(formatter.format(donGia)));
            
            loadCbbKho(sp.getMaSanPham(), maNCC);
        }
        
         
    }//GEN-LAST:event_cbbNhaCungCapActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if(tbSanPham.getSelectedRow() == -1 || cbbNhaCungCap.getSelectedItem() == null || cbbKho.getSelectedItem() == null || txtSoLuongPhanPhoi.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập đầy đủ thông tin để xác nhận!");
            return ;
        }
        int soLuongTonKho = Integer.parseInt(txtTonKho.getText().trim());
        int soLuongPP = Integer.parseInt(txtSoLuongPhanPhoi.getText().trim());
        if(soLuongPP > soLuongTonKho ){
            JOptionPane.showMessageDialog(this, "Số lượng tồn kho không đủ!");
            return ;
        }
        String tenSP = tbSanPham.getValueAt( tbSanPham.getSelectedRow(), 1).toString();
        SanPhamDTO sp = SanPhamDAO.getInstance().selectProductByName(tenSP);
        int masp = sp.getMaSanPham() ; 
        String nameNCC = cbbNhaCungCap.getSelectedItem().toString();
        NhaCungCapDTO ncc = NhaCungCapDAO.getInstance().getNCCByName(nameNCC);
        int maNCC = ncc.getMaNhaCungCap();
        
        String tenKho = cbbKho.getSelectedItem().toString() ;
        khoDTO kho = khoDAO.getInstance().getWareHouseByName(tenKho);
        int maKho = kho.getMaKho();
        
        ArrayList<ChiTietTonKhoDTO> arr = tonKhoDAO.getInstance().getListOfWareHouse(masp, maNCC);
        
        for(int i = 0; i< arr.size() ; i++){
            boolean answer = false;
            ChiTietTonKhoDTO cttk = arr.get(i);
            if(cttk.getMaKho() == maKho && cttk.getMaNhaCungCap() == maNCC && cttk.getMaSanPham() == masp){
                int soLuongUpdate = cttk.getSoLuongTonKho() - soLuongPP;
                if(tonKhoDAO.getInstance().updateSoLuong(maKho, masp, maNCC, soLuongUpdate)){
                    JOptionPane.showMessageDialog(this, "Phân phối sản phẩm thành công!");
                    answer = true ;
                } else {
                        JOptionPane.showMessageDialog(this, "Phân phối sản phẩm thất bại!");
                }
                
            }
            if(answer == true)
                return ;
        }
        

        
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtSoLuongPhanPhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongPhanPhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongPhanPhoiActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public void loadCbbKho(int maSP , int maNCC){
        modelCbbKho.removeAllElements();
        if(tbSanPham.getSelectedRow() != -1 && cbbNhaCungCap.getSelectedItem() != null){
            ArrayList<ChiTietTonKhoDTO> khoList = tonKhoDAO.getInstance().getListOfWareHouse(maSP, maNCC);
            ArrayList<ChiTietTonKhoDTO> kho = new ArrayList<>();
                for(int i =0 ;i< khoList.size() ; i++){
                    ChiTietTonKhoDTO cttk = khoList.get(i);
                    String tenKho = khoDAO.getInstance().getWareHouseByID(cttk.getMaKho());
                    if(!kho.contains(cttk)){
                        kho.add(cttk);
                        modelCbbKho.addElement(tenKho);
                    }
                    
                }
        
        }
       
    }
    public void loadCbbNhaCungCap(int maSP){
        modelCbbNcc.removeAllElements();
        int row = tbSanPham.getSelectedRow();
        ArrayList<ChiTietCungCapDTO> nccList = ChiTietCungCapDAO.getInstance().findNhaCungCapByMaSanPham(maSP);
        for(int i = 0 ; i < nccList.size() ; i++){
            ChiTietCungCapDTO ctcc = nccList.get(i);
            int maNCC = ctcc.getMaNhaCungCap();
            NhaCungCapDTO NCC = NhaCungCapDAO.getInstance().getByID(maNCC);
            modelCbbNcc.addElement(NCC.getTenNhaCungCap());
            int donGia = ctcc.getGiaNhap();
            txtDonGia.setText(String.valueOf(formatter.format(donGia)));
        }
    }
    public void loadTable(){
        ArrayList<SanPhamDTO> spList = SanPhamDAO.getInstance().getlistProduct();
        int stt = 0;
        for(int i = 0 ; i < spList.size() ; i++){
            SanPhamDTO sp = spList.get(i);
            stt ++;
            String tenSP = sp.getTenSanPham();
            Object[] row = {stt, tenSP};
            modelTable.addRow(row);
        }
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PhanPhoiProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PhanPhoiProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PhanPhoiProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PhanPhoiProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PhanPhoiProduct().setVisible(true);
//            }
//        });
//    }

    
    private DefaultComboBoxModel modelCbbNcc , modelCbbKho;
    private DefaultTableModel modelTable ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbKho;
    private javax.swing.JComboBox<String> cbbNhaCungCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKho;
    private javax.swing.JLabel labelNCC;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtDiaDiemKho;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuongPhanPhoi;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables
}
