package GUI;

import BUS.ThongKeBUS;
import DTO.NguoiDungDTO;
import DTO.ThongKe.ThongKeDoanhThuDTO;
import GUI.Chart.ModelChart;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ThongKeGUI extends javax.swing.JInternalFrame {
    private final ThongKeBUS tkBUS = new ThongKeBUS();
    private DefaultTableModel dtmOverview;
    private DefaultTableCellRenderer dtcrOverview;
    
    /**
     * Creates new form ThongKeGUI
     */
    public ThongKeGUI(NguoiDungDTO user) {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        initTable();
        setUpChart();
        thongKeDoanhThu7NgayQua();

        // Authorize
        // ...
    }
    
    public ThongKeGUI() {
        initComponents();
    }
    
    public void setUpChart() {
        chartOverview.addLegend("Chi phí", new Color(245, 189, 135));
        chartOverview.addLegend("Doanh thu", new Color(135, 189, 245));
        chartOverview.addLegend("Lợi nhuận", new Color(189, 135, 245));
    }
    
    private void initTable() {
        dtmOverview = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Chi phí", "Doanh thu", "Lợi nhuận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tbOverview.setModel(dtmOverview);
        dtcrOverview = new DefaultTableCellRenderer();
        dtcrOverview.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    public void thongKeDoanhThu7NgayQua() {
        // Get data
        ArrayList<ThongKeDoanhThuDTO> arr = new ArrayList<>();
        try {
            arr = tkBUS.thongKeDoanhThu7NgayQua();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(ThongKeGUI.this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ThongKeGUI.this, "Lỗi không xác định", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }
        
        dtmOverview.setRowCount(0);
        for (int i = 0; i < arr.size(); ++i) {
            ThongKeDoanhThuDTO tkdtDTO = arr.get(i);
            Date ngay = tkdtDTO.getNgay();
            Long chiPhi = tkdtDTO.getChiPhi();
            Long doanhThu = tkdtDTO.getDoanhThu();
            Long loiNhuan = tkdtDTO.getLoiNhuan();
            Object [] row = {ngay, chiPhi, doanhThu, loiNhuan};
            dtmOverview.addRow(row);
            chartOverview.addData(new ModelChart(ngay.toString(), new double[]{chiPhi, doanhThu, loiNhuan}));
        }
        
        for (int i = 0; i < tbOverview.getColumnCount(); ++i){
            tbOverview.getColumnModel().getColumn(i).setCellRenderer(dtcrOverview);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContainer = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pOverview = new javax.swing.JPanel();
        pSoLuongNhap = new javax.swing.JPanel();
        txtSoLuongNhap = new javax.swing.JLabel();
        lblNhap = new javax.swing.JLabel();
        iconSanPham = new javax.swing.JLabel();
        pSoLuongXuat = new javax.swing.JPanel();
        txtSoLuongXuat = new javax.swing.JLabel();
        lblXuat = new javax.swing.JLabel();
        iconSanPham1 = new javax.swing.JLabel();
        pSoLuongTonKho = new javax.swing.JPanel();
        txtTonKho = new javax.swing.JLabel();
        lblTonKho = new javax.swing.JLabel();
        iconSanPham2 = new javax.swing.JLabel();
        pChartOverview = new javax.swing.JPanel();
        chartOverview = new GUI.Chart.Chart();
        scrollPane1 = new javax.swing.JScrollPane();
        tbOverview = new javax.swing.JTable();
        lblThongKe7NgayQua = new javax.swing.JLabel();
        pTonKho = new javax.swing.JPanel();
        pFilterTonKho = new javax.swing.JPanel();
        inputTonKho = new javax.swing.JTextField();
        cbTonKhoDate = new javax.swing.JComboBox<>();
        lblTenKho1 = new javax.swing.JLabel();
        btnReloadTonKho = new javax.swing.JButton();
        btnExportExcelTonKho = new javax.swing.JButton();
        btnChonKho = new javax.swing.JButton();
        lblTonKhoDate = new javax.swing.JLabel();
        lblKho = new javax.swing.JLabel();
        spTenKho = new javax.swing.JScrollPane();
        taTenKho = new javax.swing.JTextArea();
        scrollPane2 = new javax.swing.JScrollPane();
        tbTonKho = new javax.swing.JTable();
        pDoanhThu = new javax.swing.JPanel();
        pFilterDoanhThu = new javax.swing.JPanel();
        cbDoanhThuDate = new javax.swing.JComboBox<>();
        lblDoanhThuDate = new javax.swing.JLabel();
        toolbarDoanhThu = new javax.swing.JToolBar();
        btnReloadTonKho1 = new javax.swing.JButton();
        btnExportExcelTonKho1 = new javax.swing.JButton();
        scrollPane3 = new javax.swing.JScrollPane();
        tbDoanhThu = new javax.swing.JTable();
        chartDoanhThu = new GUI.Chart.Chart();
        pSanPham = new javax.swing.JPanel();
        pFilterSanPham = new javax.swing.JPanel();
        inputSanPham = new javax.swing.JTextField();
        cbSanPhamDate = new javax.swing.JComboBox<>();
        lblSanPhamDate = new javax.swing.JLabel();
        toolbarSanPham = new javax.swing.JToolBar();
        btnReloadSanPham = new javax.swing.JButton();
        btnExportExcelSanPham = new javax.swing.JButton();
        scrollPane4 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        pLoaiSanPham = new javax.swing.JPanel();
        pFilterLoaiSanPham = new javax.swing.JPanel();
        cbLoaiSanPhamDate = new javax.swing.JComboBox<>();
        lblLoaiSanPhamDate = new javax.swing.JLabel();
        toolbarLoaiSanPham = new javax.swing.JToolBar();
        btnReloadLoaiSanPham = new javax.swing.JButton();
        btnExportExcelLoaiSanPham = new javax.swing.JButton();
        chartLoaiSanPham = new GUI.Chart.Chart();
        scrollPane5 = new javax.swing.JScrollPane();
        tbLoaiSanPham = new javax.swing.JTable();

        setBorder(null);

        pOverview.setBackground(new java.awt.Color(255, 255, 255));

        pSoLuongNhap.setBackground(new java.awt.Color(255, 204, 0));
        pSoLuongNhap.setPreferredSize(new java.awt.Dimension(359, 102));

        txtSoLuongNhap.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        txtSoLuongNhap.setForeground(new java.awt.Color(255, 255, 255));
        txtSoLuongNhap.setText("0");

        lblNhap.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        lblNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblNhap.setText("Sản phẩm đã nhập");

        iconSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-monitor-80.png"))); // NOI18N

        javax.swing.GroupLayout pSoLuongNhapLayout = new javax.swing.GroupLayout(pSoLuongNhap);
        pSoLuongNhap.setLayout(pSoLuongNhapLayout);
        pSoLuongNhapLayout.setHorizontalGroup(
            pSoLuongNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongNhapLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconSanPham)
                .addGap(18, 18, 18)
                .addGroup(pSoLuongNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNhap)
                    .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pSoLuongNhapLayout.setVerticalGroup(
            pSoLuongNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongNhapLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pSoLuongNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSanPham)
                    .addGroup(pSoLuongNhapLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNhap)))
                .addGap(10, 10, 10))
        );

        pSoLuongXuat.setBackground(new java.awt.Color(255, 204, 0));
        pSoLuongXuat.setPreferredSize(new java.awt.Dimension(359, 102));

        txtSoLuongXuat.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        txtSoLuongXuat.setForeground(new java.awt.Color(255, 255, 255));
        txtSoLuongXuat.setText("0");

        lblXuat.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        lblXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblXuat.setText("Sản phẩm đã xuất");

        iconSanPham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-monitor-80.png"))); // NOI18N

        javax.swing.GroupLayout pSoLuongXuatLayout = new javax.swing.GroupLayout(pSoLuongXuat);
        pSoLuongXuat.setLayout(pSoLuongXuatLayout);
        pSoLuongXuatLayout.setHorizontalGroup(
            pSoLuongXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongXuatLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconSanPham1)
                .addGap(18, 18, 18)
                .addGroup(pSoLuongXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblXuat)
                    .addComponent(txtSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        pSoLuongXuatLayout.setVerticalGroup(
            pSoLuongXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongXuatLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pSoLuongXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSanPham1)
                    .addGroup(pSoLuongXuatLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblXuat)))
                .addGap(10, 10, 10))
        );

        pSoLuongTonKho.setBackground(new java.awt.Color(255, 204, 0));

        txtTonKho.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        txtTonKho.setForeground(new java.awt.Color(255, 255, 255));
        txtTonKho.setText("0");

        lblTonKho.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        lblTonKho.setForeground(new java.awt.Color(255, 255, 255));
        lblTonKho.setText("Tồn kho");

        iconSanPham2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-monitor-80.png"))); // NOI18N

        javax.swing.GroupLayout pSoLuongTonKhoLayout = new javax.swing.GroupLayout(pSoLuongTonKho);
        pSoLuongTonKho.setLayout(pSoLuongTonKhoLayout);
        pSoLuongTonKhoLayout.setHorizontalGroup(
            pSoLuongTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongTonKhoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconSanPham2)
                .addGap(18, 18, 18)
                .addGroup(pSoLuongTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTonKho)
                    .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pSoLuongTonKhoLayout.setVerticalGroup(
            pSoLuongTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSoLuongTonKhoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pSoLuongTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSanPham2)
                    .addGroup(pSoLuongTonKhoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTonKho)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pChartOverviewLayout = new javax.swing.GroupLayout(pChartOverview);
        pChartOverview.setLayout(pChartOverviewLayout);
        pChartOverviewLayout.setHorizontalGroup(
            pChartOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartOverview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pChartOverviewLayout.setVerticalGroup(
            pChartOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartOverview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        tbOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Chi phí", "Doanh thu", "Lợi nhuận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(tbOverview);
        if (tbOverview.getColumnModel().getColumnCount() > 0) {
            tbOverview.getColumnModel().getColumn(0).setResizable(false);
            tbOverview.getColumnModel().getColumn(1).setResizable(false);
            tbOverview.getColumnModel().getColumn(2).setResizable(false);
            tbOverview.getColumnModel().getColumn(3).setResizable(false);
        }

        lblThongKe7NgayQua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblThongKe7NgayQua.setText("Thống kê doanh thu 7 ngày qua");

        javax.swing.GroupLayout pOverviewLayout = new javax.swing.GroupLayout(pOverview);
        pOverview.setLayout(pOverviewLayout);
        pOverviewLayout.setHorizontalGroup(
            pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1)
                    .addGroup(pOverviewLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pChartOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pOverviewLayout.createSequentialGroup()
                        .addComponent(pSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pSoLuongTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pOverviewLayout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(lblThongKe7NgayQua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pOverviewLayout.setVerticalGroup(
            pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKe7NgayQua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pChartOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Tổng quan", pOverview);

        pTonKho.setBackground(new java.awt.Color(255, 255, 255));

        pFilterTonKho.setBackground(new java.awt.Color(255, 255, 255));
        pFilterTonKho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pFilterTonKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputTonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pFilterTonKho.add(inputTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 40));

        cbTonKhoDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTonKhoDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 ngày qua", "28 ngày qua", "90 ngày qua", "365 ngày qua", "Toàn thời gian", "2023", "2022", "Tháng 10", "Tháng 9", "Tháng 8", "Tuỳ chỉnh" }));
        pFilterTonKho.add(cbTonKhoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        lblTenKho1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTenKho1.setForeground(new java.awt.Color(0, 0, 0));
        lblTenKho1.setText("Tìm kiếm sản phẩm");
        pFilterTonKho.add(lblTenKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnReloadTonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReloadTonKho.setText("Làm mới");
        btnReloadTonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReloadTonKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReloadTonKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pFilterTonKho.add(btnReloadTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnExportExcelTonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExportExcelTonKho.setText("Xuất Excel");
        btnExportExcelTonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcelTonKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportExcelTonKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pFilterTonKho.add(btnExportExcelTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btnChonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChonKho.setText("Chọn kho");
        pFilterTonKho.add(btnChonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lblTonKhoDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTonKhoDate.setForeground(new java.awt.Color(0, 0, 0));
        lblTonKhoDate.setText("dd/mm/yyyy - dd/mm/yyyy");
        pFilterTonKho.add(lblTonKhoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblKho.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblKho.setForeground(new java.awt.Color(0, 0, 0));
        lblKho.setText("Kho");
        pFilterTonKho.add(lblKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        spTenKho.setBackground(new java.awt.Color(255, 255, 255));
        spTenKho.setBorder(null);
        spTenKho.setForeground(new java.awt.Color(255, 255, 255));
        spTenKho.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spTenKho.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        spTenKho.setOpaque(false);

        taTenKho.setEditable(false);
        taTenKho.setBackground(new java.awt.Color(255, 255, 255));
        taTenKho.setColumns(20);
        taTenKho.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taTenKho.setForeground(new java.awt.Color(0, 0, 0));
        taTenKho.setLineWrap(true);
        taTenKho.setRows(5);
        taTenKho.setText("[Tên kho]");
        taTenKho.setToolTipText("");
        taTenKho.setWrapStyleWord(true);
        taTenKho.setFocusable(false);
        taTenKho.setMargin(new java.awt.Insets(0, 0, 0, 0));
        taTenKho.setOpaque(false);
        spTenKho.setViewportView(taTenKho);

        pFilterTonKho.add(spTenKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 50));
        spTenKho.getViewport().setOpaque(false);
        spTenKho.setVisible(false);

        tbTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Tồn đầu kỳ", "Nhập trong kỳ", "Xuất trong kỳ", "Tồn cuối kỳ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane2.setViewportView(tbTonKho);
        if (tbTonKho.getColumnModel().getColumnCount() > 0) {
            tbTonKho.getColumnModel().getColumn(0).setResizable(false);
            tbTonKho.getColumnModel().getColumn(1).setResizable(false);
            tbTonKho.getColumnModel().getColumn(2).setResizable(false);
            tbTonKho.getColumnModel().getColumn(3).setResizable(false);
            tbTonKho.getColumnModel().getColumn(4).setResizable(false);
            tbTonKho.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pTonKhoLayout = new javax.swing.GroupLayout(pTonKho);
        pTonKho.setLayout(pTonKhoLayout);
        pTonKhoLayout.setHorizontalGroup(
            pTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pFilterTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTonKhoLayout.setVerticalGroup(
            pTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addComponent(pFilterTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Tồn kho", pTonKho);

        pDoanhThu.setBackground(new java.awt.Color(255, 255, 255));

        pFilterDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pFilterDoanhThu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        pFilterDoanhThu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbDoanhThuDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 ngày qua", "28 ngày qua", "90 ngày qua", "365 ngày qua", "Toàn thời gian", "2023", "2022", "Tháng 10", "Tháng 9", "Tháng 8", "Tuỳ chỉnh" }));
        pFilterDoanhThu.add(cbDoanhThuDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 210, -1));

        lblDoanhThuDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDoanhThuDate.setForeground(new java.awt.Color(0, 0, 0));
        lblDoanhThuDate.setText("dd/mm/yyyy - dd/mm/yyyy");
        pFilterDoanhThu.add(lblDoanhThuDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        toolbarDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        toolbarDoanhThu.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        toolbarDoanhThu.setRollover(true);

        btnReloadTonKho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        btnReloadTonKho1.setText("Làm mới");
        btnReloadTonKho1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReloadTonKho1.setFocusable(false);
        btnReloadTonKho1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReloadTonKho1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarDoanhThu.add(btnReloadTonKho1);

        btnExportExcelTonKho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_spreadsheet_file_40px.png"))); // NOI18N
        btnExportExcelTonKho1.setText("Xuất Excel");
        btnExportExcelTonKho1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcelTonKho1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportExcelTonKho1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarDoanhThu.add(btnExportExcelTonKho1);

        tbDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "[]", "Chi phí", "Doanh thu", "Lợi nhuận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane3.setViewportView(tbDoanhThu);
        if (tbDoanhThu.getColumnModel().getColumnCount() > 0) {
            tbDoanhThu.getColumnModel().getColumn(0).setResizable(false);
            tbDoanhThu.getColumnModel().getColumn(1).setResizable(false);
            tbDoanhThu.getColumnModel().getColumn(2).setResizable(false);
            tbDoanhThu.getColumnModel().getColumn(3).setResizable(false);
            tbDoanhThu.getColumnModel().getColumn(3).setHeaderValue("Lợi nhuận");
        }

        javax.swing.GroupLayout pDoanhThuLayout = new javax.swing.GroupLayout(pDoanhThu);
        pDoanhThu.setLayout(pDoanhThuLayout);
        pDoanhThuLayout.setHorizontalGroup(
            pDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDoanhThuLayout.createSequentialGroup()
                        .addComponent(pFilterDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(toolbarDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chartDoanhThu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pDoanhThuLayout.setVerticalGroup(
            pDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolbarDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pFilterDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Doanh thu", pDoanhThu);

        pSanPham.setBackground(new java.awt.Color(255, 255, 255));

        pFilterSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pFilterSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        pFilterSanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pFilterSanPham.add(inputSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 730, 40));

        cbSanPhamDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 ngày qua", "28 ngày qua", "90 ngày qua", "365 ngày qua", "Toàn thời gian", "2023", "2022", "Tháng 10", "Tháng 9", "Tháng 8", "Tuỳ chỉnh" }));
        pFilterSanPham.add(cbSanPhamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 210, -1));

        lblSanPhamDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSanPhamDate.setForeground(new java.awt.Color(0, 0, 0));
        lblSanPhamDate.setText("dd/mm/yyyy - dd/mm/yyyy");
        pFilterSanPham.add(lblSanPhamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        toolbarSanPham.setBackground(new java.awt.Color(255, 255, 255));
        toolbarSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        toolbarSanPham.setRollover(true);

        btnReloadSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        btnReloadSanPham.setText("Làm mới");
        btnReloadSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReloadSanPham.setFocusable(false);
        btnReloadSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReloadSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSanPham.add(btnReloadSanPham);

        btnExportExcelSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_spreadsheet_file_40px.png"))); // NOI18N
        btnExportExcelSanPham.setText("Xuất Excel");
        btnExportExcelSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcelSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportExcelSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSanPham.add(btnExportExcelSanPham);

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane4.setViewportView(tbSanPham);
        if (tbSanPham.getColumnModel().getColumnCount() > 0) {
            tbSanPham.getColumnModel().getColumn(0).setResizable(false);
            tbSanPham.getColumnModel().getColumn(1).setResizable(false);
            tbSanPham.getColumnModel().getColumn(2).setResizable(false);
            tbSanPham.getColumnModel().getColumn(2).setHeaderValue("Lợi nhuận");
        }

        javax.swing.GroupLayout pSanPhamLayout = new javax.swing.GroupLayout(pSanPham);
        pSanPham.setLayout(pSanPhamLayout);
        pSanPhamLayout.setHorizontalGroup(
            pSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane4)
                    .addGroup(pSanPhamLayout.createSequentialGroup()
                        .addComponent(pFilterSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(toolbarSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pSanPhamLayout.setVerticalGroup(
            pSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolbarSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pFilterSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Sản phẩm", pSanPham);

        pLoaiSanPham.setBackground(new java.awt.Color(255, 255, 255));

        pFilterLoaiSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pFilterLoaiSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        pFilterLoaiSanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbLoaiSanPhamDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 ngày qua", "28 ngày qua", "90 ngày qua", "365 ngày qua", "Toàn thời gian", "2023", "2022", "Tháng 10", "Tháng 9", "Tháng 8", "Tuỳ chỉnh" }));
        pFilterLoaiSanPham.add(cbLoaiSanPhamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 210, -1));

        lblLoaiSanPhamDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLoaiSanPhamDate.setForeground(new java.awt.Color(0, 0, 0));
        lblLoaiSanPhamDate.setText("dd/mm/yyyy - dd/mm/yyyy");
        pFilterLoaiSanPham.add(lblLoaiSanPhamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        toolbarLoaiSanPham.setBackground(new java.awt.Color(255, 255, 255));
        toolbarLoaiSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        toolbarLoaiSanPham.setRollover(true);

        btnReloadLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        btnReloadLoaiSanPham.setText("Làm mới");
        btnReloadLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReloadLoaiSanPham.setFocusable(false);
        btnReloadLoaiSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReloadLoaiSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarLoaiSanPham.add(btnReloadLoaiSanPham);

        btnExportExcelLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_spreadsheet_file_40px.png"))); // NOI18N
        btnExportExcelLoaiSanPham.setText("Xuất Excel");
        btnExportExcelLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcelLoaiSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportExcelLoaiSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarLoaiSanPham.add(btnExportExcelLoaiSanPham);

        tbLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Loại sản phẩm", "Số lượng xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane5.setViewportView(tbLoaiSanPham);
        if (tbLoaiSanPham.getColumnModel().getColumnCount() > 0) {
            tbLoaiSanPham.getColumnModel().getColumn(0).setResizable(false);
            tbLoaiSanPham.getColumnModel().getColumn(1).setResizable(false);
            tbLoaiSanPham.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pLoaiSanPhamLayout = new javax.swing.GroupLayout(pLoaiSanPham);
        pLoaiSanPham.setLayout(pLoaiSanPhamLayout);
        pLoaiSanPhamLayout.setHorizontalGroup(
            pLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoaiSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(scrollPane5)
                    .addGroup(pLoaiSanPhamLayout.createSequentialGroup()
                        .addComponent(pFilterLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(toolbarLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pLoaiSanPhamLayout.setVerticalGroup(
            pLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoaiSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolbarLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pFilterLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Loại sản phẩm", pLoaiSanPham);

        javax.swing.GroupLayout pContainerLayout = new javax.swing.GroupLayout(pContainer);
        pContainer.setLayout(pContainerLayout);
        pContainerLayout.setHorizontalGroup(
            pContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContainerLayout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pContainerLayout.setVerticalGroup(
            pContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonKho;
    private javax.swing.JButton btnExportExcelLoaiSanPham;
    private javax.swing.JButton btnExportExcelSanPham;
    private javax.swing.JButton btnExportExcelTonKho;
    private javax.swing.JButton btnExportExcelTonKho1;
    private javax.swing.JButton btnReloadLoaiSanPham;
    private javax.swing.JButton btnReloadSanPham;
    private javax.swing.JButton btnReloadTonKho;
    private javax.swing.JButton btnReloadTonKho1;
    private javax.swing.JComboBox<String> cbDoanhThuDate;
    private javax.swing.JComboBox<String> cbLoaiSanPhamDate;
    private javax.swing.JComboBox<String> cbSanPhamDate;
    private javax.swing.JComboBox<String> cbTonKhoDate;
    private GUI.Chart.Chart chartDoanhThu;
    private GUI.Chart.Chart chartLoaiSanPham;
    private GUI.Chart.Chart chartOverview;
    private javax.swing.JLabel iconSanPham;
    private javax.swing.JLabel iconSanPham1;
    private javax.swing.JLabel iconSanPham2;
    private javax.swing.JTextField inputSanPham;
    private javax.swing.JTextField inputTonKho;
    private javax.swing.JLabel lblDoanhThuDate;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblLoaiSanPhamDate;
    private javax.swing.JLabel lblNhap;
    private javax.swing.JLabel lblSanPhamDate;
    private javax.swing.JLabel lblTenKho1;
    private javax.swing.JLabel lblThongKe7NgayQua;
    private javax.swing.JLabel lblTonKho;
    private javax.swing.JLabel lblTonKhoDate;
    private javax.swing.JLabel lblXuat;
    private javax.swing.JPanel pChartOverview;
    private javax.swing.JPanel pContainer;
    private javax.swing.JPanel pDoanhThu;
    private javax.swing.JPanel pFilterDoanhThu;
    private javax.swing.JPanel pFilterLoaiSanPham;
    private javax.swing.JPanel pFilterSanPham;
    private javax.swing.JPanel pFilterTonKho;
    private javax.swing.JPanel pLoaiSanPham;
    private javax.swing.JPanel pOverview;
    private javax.swing.JPanel pSanPham;
    private javax.swing.JPanel pSoLuongNhap;
    private javax.swing.JPanel pSoLuongTonKho;
    private javax.swing.JPanel pSoLuongXuat;
    private javax.swing.JPanel pTonKho;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JScrollPane scrollPane3;
    private javax.swing.JScrollPane scrollPane4;
    private javax.swing.JScrollPane scrollPane5;
    private javax.swing.JScrollPane spTenKho;
    private javax.swing.JTextArea taTenKho;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tbDoanhThu;
    private javax.swing.JTable tbLoaiSanPham;
    private javax.swing.JTable tbOverview;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTable tbTonKho;
    private javax.swing.JToolBar toolbarDoanhThu;
    private javax.swing.JToolBar toolbarLoaiSanPham;
    private javax.swing.JToolBar toolbarSanPham;
    private javax.swing.JLabel txtSoLuongNhap;
    private javax.swing.JLabel txtSoLuongXuat;
    private javax.swing.JLabel txtTonKho;
    // End of variables declaration//GEN-END:variables
}
