/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.SanPhamBUS;
import DAO.SanPhamDAO;
import DAO.loaiSanPhamDAO;
import DTO.SanPhamDTO;
import DTO.loaiSanPhamDTO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class UpdateProduct extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    
    private ProductForm owner;
    DecimalFormat formatterE = new DecimalFormat("0");
    int idProduct;
    SanPhamBUS spBUS = new SanPhamBUS();
    
    public UpdateProduct(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (ProductForm) parent;
        initComponents();
        setLocationRelativeTo(null);
        addCbbThuonghieu();
        
            SanPhamDTO sp = this.owner.getDetailSanPham();
            idProduct = sp.getMaSanPham();
            txtTenSanPham.setText(sp.getTenSanPham());
            txtOcung.setText(sp.getoCung());
            txtCPU.setText(sp.getCpu());
            txtDonGia.setText(String.valueOf(sp.getGiaXuat()));
            txtRAM.setText(sp.getRam());
            txtTrongLuong.setText(String.valueOf(sp.getTrongLuong()));
            txtMauSac.setText(sp.getMauSac());
            txtOS.setText(sp.getOs());
            int maLSP = sp.getLoaiSanPham();
            String lsp = loaiSanPhamDAO.getInstance().getNameOfType(maLSP);
            cbxloaisp.setSelectedItem(lsp);
            txtKichThuocMan.setText(String.valueOf(sp.getManHinh()));
            txtDungLuongPin.setText(sp.getPin());
            txtVGA.setText(sp.getVga());
        
    }
    
    private UpdateProduct(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOcung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCPU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRAM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDungLuongPin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxloaisp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        txtVGA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSaveChanged = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTrongLuong = new javax.swing.JTextField();
        txtKichThuocMan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh sửa sản phẩm");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1180, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Tên sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 19, -1, -1));

        txtTenSanPham.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtTenSanPham.setMaximumSize(new java.awt.Dimension(70, 31));
        txtTenSanPham.setMinimumSize(new java.awt.Dimension(70, 31));
        txtTenSanPham.setName(""); // NOI18N
        jPanel1.add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 40, 330, 32));

        jLabel4.setText("VGA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 88, 82, -1));

        txtOcung.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtOcung.setPreferredSize(new java.awt.Dimension(300, 31));
        jPanel1.add(txtOcung, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 261, 330, 32));

        jLabel6.setText("CPU");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 19, 37, -1));

        txtCPU.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtCPU.setMaximumSize(new java.awt.Dimension(68, 31));
        jPanel1.add(txtCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 47, 300, 32));

        jLabel7.setText("RAM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 85, 37, -1));

        txtRAM.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtRAM.setMaximumSize(new java.awt.Dimension(68, 31));
        jPanel1.add(txtRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 109, 300, 32));

        jLabel8.setText("Trọng lượng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 160, -1, -1));

        txtDungLuongPin.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtDungLuongPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDungLuongPinActionPerformed(evt);
            }
        });
        jPanel1.add(txtDungLuongPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 340, 32));

        jLabel9.setText("Màu sắc");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 226, -1, -1));

        txtMauSac.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtMauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 261, 300, 32));

        jLabel10.setText("Loại sản phẩm");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        cbxloaisp.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        cbxloaisp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxloaispItemStateChanged(evt);
            }
        });
        cbxloaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxloaispActionPerformed(evt);
            }
        });
        jPanel1.add(cbxloaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 340, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 88, 402, -1));

        jLabel15.setText("OS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 56, -1));

        txtOS.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtOS.setPreferredSize(new java.awt.Dimension(300, 31));
        jPanel1.add(txtOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 340, 33));

        txtVGA.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtVGA.setPreferredSize(new java.awt.Dimension(300, 31));
        jPanel1.add(txtVGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 107, 330, 35));

        jLabel16.setText("Giá xuất");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 154, 59, -1));

        txtDonGia.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtDonGia.setPreferredSize(new java.awt.Dimension(300, 31));
        jPanel1.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 182, 330, 32));

        jLabel17.setText("Ổ cứng");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 226, 59, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnSaveChanged.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnSaveChanged.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaveChanged.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveChanged.setText("LƯU");
        btnSaveChanged.setBorder(null);
        btnSaveChanged.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveChanged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangedActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("HỦY");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnSaveChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 339, -1, -1));

        jLabel2.setText("Kích thước màn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        jLabel5.setText("Dung lượng pin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 93, -1));

        txtTrongLuong.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtTrongLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrongLuongActionPerformed(evt);
            }
        });
        jPanel1.add(txtTrongLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 300, 32));

        txtKichThuocMan.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtKichThuocMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKichThuocManActionPerformed(evt);
            }
        });
        jPanel1.add(txtKichThuocMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 340, 32));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHỈNH SỬA THÔNG TIN SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveChangedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangedActionPerformed
        // TODO add your handling code here:
        String tenMay = txtTenSanPham.getText();
        String manhinh = txtKichThuocMan.getText();
        String cpu = txtCPU.getText();
        String ram = txtRAM.getText();
        String vga = txtVGA.getText();
        String tluong = txtTrongLuong.getText();
        String mausac = txtMauSac.getText();
        String os = txtOS.getText();
        String ocung = txtOcung.getText();
        String dungluongpin = txtDungLuongPin.getText();
        if ( tenMay.equals("") || cpu.equals("") || txtDonGia.getText().equals("")|| ram.equals("") || vga.equals("") || mausac.equals("") ||ocung.equals("") || dungluongpin.equals("") || os.equals("") || manhinh.equals("") || tluong.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
            return ;
        } 
        try {
             Integer.valueOf(txtDonGia.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá xuất ở dạng số nguyên !");
            return;
        }
        
        try {
            Float.valueOf(tluong);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập trọng lượng ở dạng số !");
            return;
        }
        
        if(Float.parseFloat(tluong) <= 0 ){
            JOptionPane.showMessageDialog(this, "Trọng lượng máy không hợp lệ. Vui lòng kiểm tra lại!");
            return ;
        }
        if(Integer.parseInt(txtDonGia.getText()) <= 0){
            JOptionPane.showMessageDialog(this, "Giá xuất không hợp lệ. Vui lòng kiểm tra lại!");
            return ;
        }
        
        if(SanPhamDAO.getInstance().getNameExceptThisID(tenMay,idProduct)){
            JOptionPane.showMessageDialog(this, "Tên sản phẩm đã tồn tại. Vui lòng chọn tên sản phẩm khác!");
            return ;
        }
        
            float trongluong = Float.parseFloat(tluong);
            int dongia = Integer.parseInt(txtDonGia.getText());
            SanPhamDTO spDTO = new SanPhamDTO();
            spDTO.setMaSanPham(idProduct);
            spDTO.setTenSanPham(tenMay);
            int maSo = loaiSanPhamDAO.getInstance().getIDOfType(cbxloaisp.getSelectedItem().toString());
            spDTO.setLoaiSanPham(maSo);
            spDTO.setGiaXuat(dongia);
            spDTO.setSoLuong(0);
            spDTO.setManHinh(manhinh);
            spDTO.setOs(os);
            spDTO.setCpu(cpu);
            spDTO.setPin(dungluongpin);
            spDTO.setoCung(ocung);
            spDTO.setMauSac(mausac);
            spDTO.setRam(ram);
            spDTO.setVga(vga);
            spDTO.setTrongLuong(trongluong);

            try {
                this.dispose();
                JOptionPane.showMessageDialog(this, spBUS.updateProduct(spDTO));
                owner.loadDataToTable();
            } catch (Exception e) {
                System.out.println(e);;
            }
        

    }//GEN-LAST:event_btnSaveChangedActionPerformed

    private void cbxloaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxloaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxloaispActionPerformed

    private void cbxloaispItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxloaispItemStateChanged

    }//GEN-LAST:event_cbxloaispItemStateChanged

    private void txtDungLuongPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDungLuongPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDungLuongPinActionPerformed

    private void txtTrongLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrongLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrongLuongActionPerformed

    private void txtKichThuocManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKichThuocManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKichThuocManActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void addCbbThuonghieu(){
        modalCbb = (DefaultComboBoxModel) cbxloaisp.getModel();
        ArrayList<loaiSanPhamDTO> lsp = loaiSanPhamDAO.getInstance().getTypeOfProduct();
        for(int i = 0; i < lsp.size() ; i++){
            loaiSanPhamDTO item = lsp.get(i);
            modalCbb.addElement(item.getTenLoaiSanPham());
        }
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateProduct dialog = new UpdateProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private DefaultComboBoxModel modalCbb ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveChanged;
    private javax.swing.JComboBox<String> cbxloaisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDungLuongPin;
    private javax.swing.JTextField txtKichThuocMan;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtOcung;
    private javax.swing.JTextField txtRAM;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTrongLuong;
    private javax.swing.JTextField txtVGA;
    // End of variables declaration//GEN-END:variables
}
