/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Dialog;

import BUS.SanPhamBUS;
import BUS.SearchProduct;
import DAO.SanPhamDAO;
import DAO.loaiSanPhamDAO;
import DTO.SanPhamDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class ActiveProduct extends javax.swing.JFrame {

    /**
     * Creates new form ActiveProduct
     */
    SanPhamBUS spBUS = new SanPhamBUS();
    public ActiveProduct() {
        initComponents();
        modelTable = (DefaultTableModel) tbSanPham.getModel();
        modelCombobox = (DefaultComboBoxModel)cbbActive.getModel();
        tbSanPham.setDefaultEditor(Object.class, null);
        renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbSanPham.setDefaultRenderer(String.class, renderer);
        cbbActive.setSelectedItem("Hoạt động");
        ArrayList<SanPhamDTO> arr = SanPhamDAO.getInstance().getlistProduct();
        loadTable(arr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHoatDong = new javax.swing.JButton();
        btnNgungHoatDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbbActive = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trạng thái hoạt động");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHoatDong.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnHoatDong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        btnHoatDong.setText("HOẠT ĐỘNG");
        btnHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoatDongActionPerformed(evt);
            }
        });

        btnNgungHoatDong.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnNgungHoatDong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNgungHoatDong.setForeground(new java.awt.Color(255, 255, 255));
        btnNgungHoatDong.setText("NGỪNG HOẠT ĐỘNG");
        btnNgungHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgungHoatDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(btnHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnNgungHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNgungHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.getTableHeader().setResizingAllowed(false);
        tbSanPham.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSanPham);
        if (tbSanPham.getColumnModel().getColumnCount() > 0) {
            tbSanPham.getColumnModel().getColumn(0).setResizable(false);
            tbSanPham.getColumnModel().getColumn(1).setResizable(false);
            tbSanPham.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_25px.png"))); // NOI18N
        jButton1.setBorder(null);

        cbbActive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Ngừng hoạt động" }));
        cbbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbbActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbActive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoatDongActionPerformed
        // TODO add your handling code here:
        int row = tbSanPham.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn kinh doanh!");
            return ;
        }
        String tenSP = tbSanPham.getValueAt(row, 1).toString();
        SanPhamDTO SP = SanPhamDAO.getInstance().selectDeletedProductByName(tenSP);
        if(loaiSanPhamDAO.getInstance().getNameOfType(SP.getMaLoaiSanPham()).equals("")){
            JOptionPane.showMessageDialog(this, "Thương hiệu của sản phẩm này không tồn tại!");
            return ;
        }
        JOptionPane.showMessageDialog(this,spBUS.reuseProduct(SP.getMaSanPham()) );
        ArrayList<SanPhamDTO> arr = SanPhamDAO.getInstance().getUnuselistProduct();
        loadTable(arr);
    }//GEN-LAST:event_btnHoatDongActionPerformed

    private void cbbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbActiveActionPerformed
        // TODO add your handling code here:
        if(cbbActive.getSelectedItem() == "Hoạt động"){
            ArrayList<SanPhamDTO> arr = SanPhamDAO.getInstance().getlistProduct();
            loadTable(arr);
            btnHoatDong.setEnabled(false);
            btnNgungHoatDong.setEnabled(true);
        } else {
            ArrayList<SanPhamDTO> arr = SanPhamDAO.getInstance().getUnuselistProduct();
            loadTable(arr);
            btnNgungHoatDong.setEnabled(false);
            btnHoatDong.setEnabled(true);
        }
    }//GEN-LAST:event_cbbActiveActionPerformed

    private void btnNgungHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgungHoatDongActionPerformed
        // TODO add your handling code here:
        int row = tbSanPham.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn ngừng kinh doanh!");
            return ;
        }
        String tenSP = tbSanPham.getValueAt(row, 1).toString();
        SanPhamDTO SP = SanPhamDAO.getInstance().selectProductByName(tenSP);
        JOptionPane.showMessageDialog(this,spBUS.deleteProduct(SP.getMaSanPham()) );
        ArrayList<SanPhamDTO> arr = SanPhamDAO.getInstance().getlistProduct();
        loadTable(arr);
    }//GEN-LAST:event_btnNgungHoatDongActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String content = txtSearch.getText();
        if(cbbActive.getSelectedItem() == "Hoạt động"){
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchTenSanPham(content);
            loadTable(result);
        } else {
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchDeletedTenSanPham(content);
            loadTable(result);
        }
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        String content = txtSearch.getText();
        if(cbbActive.getSelectedItem() == "Hoạt động"){
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchTenSanPham(content);
            loadTable(result);
        } else {
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchDeletedTenSanPham(content);
            loadTable(result);
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
        String content = txtSearch.getText();
        if(cbbActive.getSelectedItem() == "Hoạt động"){
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchTenSanPham(content);
            loadTable(result);
        } else {
            ArrayList<SanPhamDTO> result = SearchProduct.getInstance().searchDeletedTenSanPham(content);
            loadTable(result);
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    /**
     * @param args the command line arguments
     */
    
    public void loadTable(ArrayList<SanPhamDTO> arr){
        modelTable.setRowCount(0);
        for(int i = 0; i< arr.size(); i++){
                SanPhamDTO spDTO = arr.get(i);
                Object[] row ={spDTO.getMaSanPham(),spDTO.getTenSanPham()};
                modelTable.addRow(row); 
        }
        for(int i = 0; i < tbSanPham.getColumnCount(); i++){
            
            tbSanPham.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActiveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActiveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActiveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActiveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActiveProduct().setVisible(true);
            }
        });
    }
    
    DefaultTableCellRenderer renderer;
    private DefaultTableModel modelTable ;
    private DefaultComboBoxModel modelCombobox ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoatDong;
    private javax.swing.JButton btnNgungHoatDong;
    private javax.swing.JComboBox<String> cbbActive;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
