package GUI.Dialog.Chart;

import DTO.DateRangeDTO;
import DTO.ThongKe.ThongKeLoaiSanPhamDTO;
import helper.DateHelper;
import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.style.Styler.LegendPosition;

public class LoaiSanPhamChart extends javax.swing.JFrame {
    private ArrayList<ThongKeLoaiSanPhamDTO> arr;
    private List<String> listLoaiSanPham = new ArrayList<>();
    private List<Integer> listSoLuongXuat = new ArrayList<>();
    private DateRangeDTO dateRange;
    
    public LoaiSanPhamChart() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public LoaiSanPhamChart(ArrayList<ThongKeLoaiSanPhamDTO> arr, DateRangeDTO dateRange) {
        initComponents();
        setLocationRelativeTo(null);
        this.arr = arr;
        this.dateRange = dateRange;
        separateData();
        displayChart();
        
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent evt) {
                displayChart();
            }
        });
    }
    
    private void separateData() {
        for (int i = 0; i < arr.size(); ++i) {
            listLoaiSanPham.add(arr.get(i).getTenLoaiSanPham());
            listSoLuongXuat.add(arr.get(i).getSoLuong());
        }
    }
    
    private CategoryChart getChart() {
        CategoryChart chart = new CategoryChartBuilder().width(800).height(600)
                .title(this.dateRange.getFromDate().format(DateHelper.DATE_FORMATTER) + " - " + this.dateRange.getToDate().format(DateHelper.DATE_FORMATTER))
                .xAxisTitle("Loại sản phẩm").yAxisTitle("Số lượng xuất").build();

        // Customize Chart
//        chart.getStyler().setLegendPosition(LegendPosition.InsideNW);

        // Series
        chart.addSeries("Loại sản phẩm", listLoaiSanPham, listSoLuongXuat);

        return chart;
    }
    
    public void displayChart() {
        JPanel chartPanel = new XChartPanel<CategoryChart>(getChart());
        pChartContainer.removeAll();
        pChartContainer.add(chartPanel, BorderLayout.CENTER);
        pChartContainer.repaint();
        pChartContainer.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pChartContainer = new javax.swing.JPanel();
        placeholder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê loại sản phẩm");

        pChartContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout placeholderLayout = new javax.swing.GroupLayout(placeholder);
        placeholder.setLayout(placeholderLayout);
        placeholderLayout.setHorizontalGroup(
            placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        placeholderLayout.setVerticalGroup(
            placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        pChartContainer.add(placeholder, java.awt.BorderLayout.CENTER);

        getContentPane().add(pChartContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiSanPhamChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pChartContainer;
    private javax.swing.JPanel placeholder;
    // End of variables declaration//GEN-END:variables
}
