/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.SanPhamDAO;
import DTO.NhaCungCapDTO;
import DTO.ChiTietCungCapDTO;
import DTO.SanPhamDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import OldDAO.NhaCungCapDAO;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author downny
 */
public class ChiTietCungCap extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiCungCap
     */
    


    public ChiTietCungCap(NhaCungCapDTO ncc) {
        initComponents();
        txtTenNCC.setEditable(false);

        tbModel =(DefaultTableModel) tbSanPham.getModel();
        tbSanPham.setDefaultEditor(Object.class, null);
        
        int id = ncc.getMaNhaCungCap();
        txtTenNCC.setText(ncc.getTenNhaCungCap());
        LoadDataToTable(id);
        
        setResizable(false);
    }
    
    public void LoadDataToTable(int id){
        ccsp = NhaCungCapDAO.getInstance().getListChiTietCungCap(id);
        tbModel.setRowCount(0);
        for(int i = 0; i < ccsp.size(); i++){
            ChiTietCungCapDTO ql = ccsp.get(i);
            int stt = i + 1;
            SanPhamDTO sp = SanPhamDAO.getInstance().selectProductByID(ql.getMaSanPham());
            tbModel.addRow(new Object[]{
             stt, ql.getMaSanPham(), sp.getTenSanPham(), ql.getGiaNhap()
        });
        }
        for(int i = 0; i < tbSanPham.getColumnCount(); i++){           
             DefaultTableCellRenderer renderer;
            renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(SwingConstants.CENTER);
            tbSanPham.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        lbNCC = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN SẢN PHẨM");
        panel1.add(jLabel1);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNCC.setText("Nhà cung cấp : ");
        panel2.add(lbNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        panel2.add(txtTenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 310, 30));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Giá nhập"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSanPhamMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 880, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tbSanPhamMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn thoát không?","Warning",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION){
           this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    private DefaultTableModel tbModel;
    private ArrayList<ChiTietCungCapDTO> ccsp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNCC;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
